import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "../../styles/Home.module.css";
import { connectEthereum } from "../ethereum";
import styled from "styled-components";

export const Container = styled.div`
  width: 100vw;
  height: 100vh;
  background-color: yellowgreen;
  padding: 10px;

  display: flex;
  flex-direction: column;
`;

export const Header = styled.div`
  width: 100%;
  height: 70px;
  background-color: purple;
  margin-bottom: 10px;
`;

export const Main = styled.div``;

export default function Home() {
  //
  useEffect(() => {
    const done = async () => {
      const [account, netId] = await connectEthereum();
    };
    done();
  }, []);

  return (
    <Container className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <Header></Header>
    </Container>
  );
}
